name: Cron Job Example

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Scheduled task executed"
